# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1950, 1108)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_20.addWidget(self.label_20)
        self.labelVideoName = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.labelVideoName.setFont(font)
        self.labelVideoName.setText("")
        self.labelVideoName.setObjectName("labelVideoName")
        self.horizontalLayout_20.addWidget(self.labelVideoName)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem)
        self.verticalLayout_7.addLayout(self.horizontalLayout_20)
        self.checkBoxEncirclePartiles = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.checkBoxEncirclePartiles.setFont(font)
        self.checkBoxEncirclePartiles.setCheckable(True)
        self.checkBoxEncirclePartiles.setChecked(True)
        self.checkBoxEncirclePartiles.setObjectName("checkBoxEncirclePartiles")
        self.verticalLayout_7.addWidget(self.checkBoxEncirclePartiles)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_10.addWidget(self.label_12)
        self.spinBoxFrameIndex = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBoxFrameIndex.setObjectName("spinBoxFrameIndex")
        self.horizontalLayout_10.addWidget(self.spinBoxFrameIndex)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem1)
        self.verticalLayout_7.addLayout(self.horizontalLayout_10)
        self.horizontalSliderFrameIndex = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSliderFrameIndex.setMaximum(9999)
        self.horizontalSliderFrameIndex.setPageStep(100)
        self.horizontalSliderFrameIndex.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderFrameIndex.setObjectName("horizontalSliderFrameIndex")
        self.verticalLayout_7.addWidget(self.horizontalSliderFrameIndex)
        self.image_item = ImageView(self.centralwidget)
        self.image_item.setMinimumSize(QtCore.QSize(1280, 960))
        self.image_item.setObjectName("image_item")
        self.verticalLayout_7.addWidget(self.image_item)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1950, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuTracks = QtWidgets.QMenu(self.menubar)
        self.menuTracks.setObjectName("menuTracks")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidgetParams = QtWidgets.QDockWidget(MainWindow)
        self.dockWidgetParams.setMinimumSize(QtCore.QSize(325, 1064))
        self.dockWidgetParams.setObjectName("dockWidgetParams")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.pushButtonLiveUpdate = QtWidgets.QPushButton(self.dockWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonLiveUpdate.setFont(font)
        self.pushButtonLiveUpdate.setCheckable(True)
        self.pushButtonLiveUpdate.setChecked(True)
        self.pushButtonLiveUpdate.setObjectName("pushButtonLiveUpdate")
        self.horizontalLayout_19.addWidget(self.pushButtonLiveUpdate)
        self.pushButtonUpdateNow = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pushButtonUpdateNow.setObjectName("pushButtonUpdateNow")
        self.horizontalLayout_19.addWidget(self.pushButtonUpdateNow)
        self.verticalLayout_9.addLayout(self.horizontalLayout_19)
        self.groupBox = QtWidgets.QGroupBox(self.dockWidgetContents)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalSliderDiameter = QtWidgets.QSlider(self.groupBox)
        self.horizontalSliderDiameter.setMinimum(1)
        self.horizontalSliderDiameter.setMaximum(99)
        self.horizontalSliderDiameter.setSingleStep(2)
        self.horizontalSliderDiameter.setProperty("value", 11)
        self.horizontalSliderDiameter.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderDiameter.setObjectName("horizontalSliderDiameter")
        self.horizontalLayout.addWidget(self.horizontalSliderDiameter)
        self.spinBoxDiameter = QtWidgets.QSpinBox(self.groupBox)
        self.spinBoxDiameter.setMinimum(1)
        self.spinBoxDiameter.setMaximum(999)
        self.spinBoxDiameter.setSingleStep(2)
        self.spinBoxDiameter.setProperty("value", 11)
        self.spinBoxDiameter.setObjectName("spinBoxDiameter")
        self.horizontalLayout.addWidget(self.spinBoxDiameter)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_5.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalSliderMinmass = QtWidgets.QSlider(self.groupBox)
        self.horizontalSliderMinmass.setMaximum(5000)
        self.horizontalSliderMinmass.setSingleStep(50)
        self.horizontalSliderMinmass.setPageStep(100)
        self.horizontalSliderMinmass.setProperty("value", 100)
        self.horizontalSliderMinmass.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderMinmass.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.horizontalSliderMinmass.setTickInterval(500)
        self.horizontalSliderMinmass.setObjectName("horizontalSliderMinmass")
        self.horizontalLayout_2.addWidget(self.horizontalSliderMinmass)
        self.spinBoxMinmass = QtWidgets.QSpinBox(self.groupBox)
        self.spinBoxMinmass.setMaximum(99999)
        self.spinBoxMinmass.setSingleStep(50)
        self.spinBoxMinmass.setProperty("value", 100)
        self.spinBoxMinmass.setObjectName("spinBoxMinmass")
        self.horizontalLayout_2.addWidget(self.spinBoxMinmass)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout_5.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalSliderMaxmass = QtWidgets.QSlider(self.groupBox)
        self.horizontalSliderMaxmass.setMaximum(5000)
        self.horizontalSliderMaxmass.setSingleStep(50)
        self.horizontalSliderMaxmass.setPageStep(100)
        self.horizontalSliderMaxmass.setProperty("value", 500)
        self.horizontalSliderMaxmass.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderMaxmass.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.horizontalSliderMaxmass.setTickInterval(500)
        self.horizontalSliderMaxmass.setObjectName("horizontalSliderMaxmass")
        self.horizontalLayout_3.addWidget(self.horizontalSliderMaxmass)
        self.spinBoxMaxmass = QtWidgets.QSpinBox(self.groupBox)
        self.spinBoxMaxmass.setMaximum(99999)
        self.spinBoxMaxmass.setSingleStep(50)
        self.spinBoxMaxmass.setProperty("value", 500)
        self.spinBoxMaxmass.setObjectName("spinBoxMaxmass")
        self.horizontalLayout_3.addWidget(self.spinBoxMaxmass)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.doubleSpinBoxMaxsize = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBoxMaxsize.setMaximum(999.99)
        self.doubleSpinBoxMaxsize.setSingleStep(0.05)
        self.doubleSpinBoxMaxsize.setProperty("value", 2.5)
        self.doubleSpinBoxMaxsize.setObjectName("doubleSpinBoxMaxsize")
        self.horizontalLayout_4.addWidget(self.doubleSpinBoxMaxsize)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.line = QtWidgets.QFrame(self.groupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.line.setFont(font)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_5.addWidget(self.line)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_5.addWidget(self.label_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.spinBoxLinkerSearchRange = QtWidgets.QSpinBox(self.groupBox)
        self.spinBoxLinkerSearchRange.setMinimum(0)
        self.spinBoxLinkerSearchRange.setMaximum(999)
        self.spinBoxLinkerSearchRange.setProperty("value", 10)
        self.spinBoxLinkerSearchRange.setObjectName("spinBoxLinkerSearchRange")
        self.horizontalLayout_5.addWidget(self.spinBoxLinkerSearchRange)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8)
        self.spinBoxLinkerMemory = QtWidgets.QSpinBox(self.groupBox)
        self.spinBoxLinkerMemory.setMaximum(999)
        self.spinBoxLinkerMemory.setProperty("value", 8)
        self.spinBoxLinkerMemory.setObjectName("spinBoxLinkerMemory")
        self.horizontalLayout_6.addWidget(self.spinBoxLinkerMemory)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.verticalLayout_9.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.dockWidgetContents)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.checkBoxGamma = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBoxGamma.setObjectName("checkBoxGamma")
        self.horizontalLayout_7.addWidget(self.checkBoxGamma)
        self.doubleSpinBoxGamma = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBoxGamma.setSingleStep(0.05)
        self.doubleSpinBoxGamma.setProperty("value", 1.0)
        self.doubleSpinBoxGamma.setObjectName("doubleSpinBoxGamma")
        self.horizontalLayout_7.addWidget(self.doubleSpinBoxGamma)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.line_2 = QtWidgets.QFrame(self.groupBox_2)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.checkBoxCLAHE = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBoxCLAHE.setChecked(True)
        self.checkBoxCLAHE.setObjectName("checkBoxCLAHE")
        self.verticalLayout.addWidget(self.checkBoxCLAHE)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_9.addWidget(self.label_9)
        self.doubleSpinBoxCLAHEClipLimit = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBoxCLAHEClipLimit.setProperty("value", 2.0)
        self.doubleSpinBoxCLAHEClipLimit.setObjectName("doubleSpinBoxCLAHEClipLimit")
        self.horizontalLayout_9.addWidget(self.doubleSpinBoxCLAHEClipLimit)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_8.addWidget(self.label_10)
        self.spinBoxGridSizeX = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBoxGridSizeX.setProperty("value", 8)
        self.spinBoxGridSizeX.setObjectName("spinBoxGridSizeX")
        self.horizontalLayout_8.addWidget(self.spinBoxGridSizeX)
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_8.addWidget(self.label_11)
        self.spinBoxGridSizeY = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBoxGridSizeY.setProperty("value", 8)
        self.spinBoxGridSizeY.setObjectName("spinBoxGridSizeY")
        self.horizontalLayout_8.addWidget(self.spinBoxGridSizeY)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.line_4 = QtWidgets.QFrame(self.groupBox_2)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout.addWidget(self.line_4)
        self.pushButtonRecreateMask = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButtonRecreateMask.setObjectName("pushButtonRecreateMask")
        self.verticalLayout.addWidget(self.pushButtonRecreateMask)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_15 = QtWidgets.QLabel(self.groupBox_2)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_13.addWidget(self.label_15)
        self.doubleSpinBoxCirclesParam1 = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBoxCirclesParam1.setMaximum(999.99)
        self.doubleSpinBoxCirclesParam1.setSingleStep(0.1)
        self.doubleSpinBoxCirclesParam1.setProperty("value", 1.2)
        self.doubleSpinBoxCirclesParam1.setObjectName("doubleSpinBoxCirclesParam1")
        self.horizontalLayout_13.addWidget(self.doubleSpinBoxCirclesParam1)
        self.verticalLayout.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_16 = QtWidgets.QLabel(self.groupBox_2)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_14.addWidget(self.label_16)
        self.spinBoxCirclesParam2 = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBoxCirclesParam2.setMinimum(1)
        self.spinBoxCirclesParam2.setMaximum(9999)
        self.spinBoxCirclesParam2.setSingleStep(10)
        self.spinBoxCirclesParam2.setProperty("value", 100)
        self.spinBoxCirclesParam2.setObjectName("spinBoxCirclesParam2")
        self.horizontalLayout_14.addWidget(self.spinBoxCirclesParam2)
        self.verticalLayout.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_17 = QtWidgets.QLabel(self.groupBox_2)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_15.addWidget(self.label_17)
        self.spinBoxMaskMinRadius = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBoxMaskMinRadius.setMinimum(1)
        self.spinBoxMaskMinRadius.setMaximum(9999)
        self.spinBoxMaskMinRadius.setSingleStep(10)
        self.spinBoxMaskMinRadius.setProperty("value", 350)
        self.spinBoxMaskMinRadius.setObjectName("spinBoxMaskMinRadius")
        self.horizontalLayout_15.addWidget(self.spinBoxMaskMinRadius)
        self.verticalLayout.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_18 = QtWidgets.QLabel(self.groupBox_2)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_16.addWidget(self.label_18)
        self.spinBoxMaskMaxRadius = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBoxMaskMaxRadius.setMinimum(1)
        self.spinBoxMaskMaxRadius.setMaximum(9999)
        self.spinBoxMaskMaxRadius.setSingleStep(10)
        self.spinBoxMaskMaxRadius.setProperty("value", 450)
        self.spinBoxMaskMaxRadius.setObjectName("spinBoxMaskMaxRadius")
        self.horizontalLayout_16.addWidget(self.spinBoxMaskMaxRadius)
        self.verticalLayout.addLayout(self.horizontalLayout_16)
        self.verticalLayout_9.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.dockWidgetContents)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.checkBoxUseNeuralNetworkModel = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBoxUseNeuralNetworkModel.setObjectName("checkBoxUseNeuralNetworkModel")
        self.verticalLayout_8.addWidget(self.checkBoxUseNeuralNetworkModel)
        self.label_19 = QtWidgets.QLabel(self.groupBox_3)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_8.addWidget(self.label_19)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.lineEditNeuralNetworkModelPath = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEditNeuralNetworkModelPath.setObjectName("lineEditNeuralNetworkModelPath")
        self.horizontalLayout_18.addWidget(self.lineEditNeuralNetworkModelPath)
        self.pushButtonChooseNeuralNetworkModel = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButtonChooseNeuralNetworkModel.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButtonChooseNeuralNetworkModel.setObjectName("pushButtonChooseNeuralNetworkModel")
        self.horizontalLayout_18.addWidget(self.pushButtonChooseNeuralNetworkModel)
        self.verticalLayout_8.addLayout(self.horizontalLayout_18)
        self.verticalLayout_9.addWidget(self.groupBox_3)
        self.label_21 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_9.addWidget(self.label_21)
        self.lineEditCurrentItemName = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.lineEditCurrentItemName.setObjectName("lineEditCurrentItemName")
        self.verticalLayout_9.addWidget(self.lineEditCurrentItemName)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.pushButtonProcessNow = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pushButtonProcessNow.setObjectName("pushButtonProcessNow")
        self.horizontalLayout_17.addWidget(self.pushButtonProcessNow)
        self.pushButtonAddToBatch = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pushButtonAddToBatch.setObjectName("pushButtonAddToBatch")
        self.horizontalLayout_17.addWidget(self.pushButtonAddToBatch)
        self.verticalLayout_9.addLayout(self.horizontalLayout_17)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem3)
        self.dockWidgetParams.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidgetParams)
        self.dockWidgetBatch = QtWidgets.QDockWidget(MainWindow)
        self.dockWidgetBatch.setMinimumSize(QtCore.QSize(325, 169))
        self.dockWidgetBatch.setObjectName("dockWidgetBatch")
        self.dockWidgetContents_2 = QtWidgets.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.dockWidgetContents_2)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.listWidgetBatch = QtWidgets.QListWidget(self.dockWidgetContents_2)
        self.listWidgetBatch.setObjectName("listWidgetBatch")
        self.verticalLayout_6.addWidget(self.listWidgetBatch)
        self.dockWidgetBatch.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidgetBatch)
        self.actionOpen_Video = QtWidgets.QAction(MainWindow)
        self.actionOpen_Video.setObjectName("actionOpen_Video")
        self.actionExport_Annotated_Video = QtWidgets.QAction(MainWindow)
        self.actionExport_Annotated_Video.setObjectName("actionExport_Annotated_Video")
        self.actionOpen_Batch = QtWidgets.QAction(MainWindow)
        self.actionOpen_Batch.setObjectName("actionOpen_Batch")
        self.actionSave_Batch = QtWidgets.QAction(MainWindow)
        self.actionSave_Batch.setObjectName("actionSave_Batch")
        self.actionLoad_Parameters = QtWidgets.QAction(MainWindow)
        self.actionLoad_Parameters.setObjectName("actionLoad_Parameters")
        self.actionSave_Parameters = QtWidgets.QAction(MainWindow)
        self.actionSave_Parameters.setObjectName("actionSave_Parameters")
        self.actionExport_Training_Dataset = QtWidgets.QAction(MainWindow)
        self.actionExport_Training_Dataset.setObjectName("actionExport_Training_Dataset")
        self.actionView_Statistics = QtWidgets.QAction(MainWindow)
        self.actionView_Statistics.setObjectName("actionView_Statistics")
        self.menuFile.addAction(self.actionOpen_Video)
        self.menuFile.addAction(self.actionExport_Annotated_Video)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionOpen_Batch)
        self.menuFile.addAction(self.actionSave_Batch)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionLoad_Parameters)
        self.menuFile.addAction(self.actionSave_Parameters)
        self.menuTracks.addAction(self.actionView_Statistics)
        self.menuTracks.addSeparator()
        self.menuTracks.addAction(self.actionExport_Training_Dataset)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuTracks.menuAction())

        self.retranslateUi(MainWindow)
        self.horizontalSliderDiameter.valueChanged['int'].connect(self.spinBoxDiameter.setValue)
        self.spinBoxDiameter.valueChanged['int'].connect(self.horizontalSliderDiameter.setValue)
        self.horizontalSliderMinmass.valueChanged['int'].connect(self.spinBoxMinmass.setValue)
        self.spinBoxMinmass.valueChanged['int'].connect(self.horizontalSliderMinmass.setValue)
        self.horizontalSliderMaxmass.valueChanged['int'].connect(self.spinBoxMaxmass.setValue)
        self.spinBoxMaxmass.valueChanged['int'].connect(self.horizontalSliderMaxmass.setValue)
        self.horizontalSliderFrameIndex.valueChanged['int'].connect(self.spinBoxFrameIndex.setValue)
        self.spinBoxFrameIndex.valueChanged['int'].connect(self.horizontalSliderFrameIndex.setValue)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.pushButtonLiveUpdate, self.pushButtonUpdateNow)
        MainWindow.setTabOrder(self.pushButtonUpdateNow, self.horizontalSliderDiameter)
        MainWindow.setTabOrder(self.horizontalSliderDiameter, self.spinBoxDiameter)
        MainWindow.setTabOrder(self.spinBoxDiameter, self.horizontalSliderMinmass)
        MainWindow.setTabOrder(self.horizontalSliderMinmass, self.spinBoxMinmass)
        MainWindow.setTabOrder(self.spinBoxMinmass, self.horizontalSliderMaxmass)
        MainWindow.setTabOrder(self.horizontalSliderMaxmass, self.spinBoxMaxmass)
        MainWindow.setTabOrder(self.spinBoxMaxmass, self.doubleSpinBoxMaxsize)
        MainWindow.setTabOrder(self.doubleSpinBoxMaxsize, self.spinBoxLinkerSearchRange)
        MainWindow.setTabOrder(self.spinBoxLinkerSearchRange, self.spinBoxLinkerMemory)
        MainWindow.setTabOrder(self.spinBoxLinkerMemory, self.checkBoxGamma)
        MainWindow.setTabOrder(self.checkBoxGamma, self.doubleSpinBoxGamma)
        MainWindow.setTabOrder(self.doubleSpinBoxGamma, self.checkBoxCLAHE)
        MainWindow.setTabOrder(self.checkBoxCLAHE, self.doubleSpinBoxCLAHEClipLimit)
        MainWindow.setTabOrder(self.doubleSpinBoxCLAHEClipLimit, self.spinBoxGridSizeX)
        MainWindow.setTabOrder(self.spinBoxGridSizeX, self.spinBoxGridSizeY)
        MainWindow.setTabOrder(self.spinBoxGridSizeY, self.doubleSpinBoxCirclesParam1)
        MainWindow.setTabOrder(self.doubleSpinBoxCirclesParam1, self.spinBoxCirclesParam2)
        MainWindow.setTabOrder(self.spinBoxCirclesParam2, self.spinBoxMaskMinRadius)
        MainWindow.setTabOrder(self.spinBoxMaskMinRadius, self.spinBoxMaskMaxRadius)
        MainWindow.setTabOrder(self.spinBoxMaskMaxRadius, self.checkBoxUseNeuralNetworkModel)
        MainWindow.setTabOrder(self.checkBoxUseNeuralNetworkModel, self.lineEditNeuralNetworkModelPath)
        MainWindow.setTabOrder(self.lineEditNeuralNetworkModelPath, self.pushButtonChooseNeuralNetworkModel)
        MainWindow.setTabOrder(self.pushButtonChooseNeuralNetworkModel, self.lineEditCurrentItemName)
        MainWindow.setTabOrder(self.lineEditCurrentItemName, self.pushButtonProcessNow)
        MainWindow.setTabOrder(self.pushButtonProcessNow, self.pushButtonAddToBatch)
        MainWindow.setTabOrder(self.pushButtonAddToBatch, self.checkBoxEncirclePartiles)
        MainWindow.setTabOrder(self.checkBoxEncirclePartiles, self.image_item)
        MainWindow.setTabOrder(self.image_item, self.listWidgetBatch)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_20.setText(_translate("MainWindow", "Video Name:"))
        self.checkBoxEncirclePartiles.setText(_translate("MainWindow", "Encircle particles"))
        self.label_12.setText(_translate("MainWindow", "Frame index:"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuTracks.setTitle(_translate("MainWindow", "Tracks"))
        self.dockWidgetParams.setWindowTitle(_translate("MainWindow", "Parameters"))
        self.pushButtonLiveUpdate.setText(_translate("MainWindow", "Live update"))
        self.pushButtonUpdateNow.setText(_translate("MainWindow", "Update now"))
        self.groupBox.setTitle(_translate("MainWindow", "Tracker"))
        self.label_5.setText(_translate("MainWindow", "Particles"))
        self.label.setText(_translate("MainWindow", "diameter"))
        self.label_2.setText(_translate("MainWindow", "minmass"))
        self.label_3.setText(_translate("MainWindow", "maxmass"))
        self.label_4.setText(_translate("MainWindow", "maxsize: "))
        self.label_6.setText(_translate("MainWindow", "Linker"))
        self.label_7.setToolTip(_translate("MainWindow", "the maximum distance features can move between frames"))
        self.label_7.setText(_translate("MainWindow", "Search range"))
        self.label_8.setToolTip(_translate("MainWindow", "the maximum distance features can move between frames"))
        self.label_8.setText(_translate("MainWindow", "memory"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Adjust video"))
        self.checkBoxGamma.setText(_translate("MainWindow", "Adjust Gamma"))
        self.checkBoxCLAHE.setText(_translate("MainWindow", "CLAHE"))
        self.label_9.setText(_translate("MainWindow", "clip limit"))
        self.label_10.setText(_translate("MainWindow", "grid size"))
        self.label_11.setText(_translate("MainWindow", "X"))
        self.pushButtonRecreateMask.setText(_translate("MainWindow", "Create Mask"))
        self.label_15.setText(_translate("MainWindow", "Param 1"))
        self.label_16.setText(_translate("MainWindow", "Param 2"))
        self.label_17.setText(_translate("MainWindow", "min radius"))
        self.label_18.setText(_translate("MainWindow", "max radius"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Neural Network Model"))
        self.checkBoxUseNeuralNetworkModel.setText(_translate("MainWindow", "Use model"))
        self.label_19.setText(_translate("MainWindow", "Select model file"))
        self.pushButtonChooseNeuralNetworkModel.setText(_translate("MainWindow", "..."))
        self.label_21.setText(_translate("MainWindow", "Enter name:"))
        self.pushButtonProcessNow.setText(_translate("MainWindow", "Process Now"))
        self.pushButtonAddToBatch.setText(_translate("MainWindow", "Add to batch"))
        self.dockWidgetBatch.setWindowTitle(_translate("MainWindow", "Batch"))
        self.actionOpen_Video.setText(_translate("MainWindow", "Open Video"))
        self.actionExport_Annotated_Video.setText(_translate("MainWindow", "Export Annotated Video"))
        self.actionOpen_Batch.setText(_translate("MainWindow", "Open Batch"))
        self.actionSave_Batch.setText(_translate("MainWindow", "Save Batch"))
        self.actionLoad_Parameters.setText(_translate("MainWindow", "Load Parameters"))
        self.actionSave_Parameters.setText(_translate("MainWindow", "Save Parameters"))
        self.actionExport_Training_Dataset.setText(_translate("MainWindow", "Export Training Dataset"))
        self.actionView_Statistics.setText(_translate("MainWindow", "View Statistics"))

from pyqtgraph import ImageView
